# Form implementation generated from reading ui file 'add_card_widget.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(728, 688)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.toolbar = QtWidgets.QWidget(parent=self.widget)
        self.toolbar.setObjectName("toolbar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.toolbar)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.boldButton = QtWidgets.QPushButton(parent=self.toolbar)
        self.boldButton.setCheckable(False)
        self.boldButton.setObjectName("boldButton")
        self.horizontalLayout_3.addWidget(self.boldButton)
        self.italicButton = QtWidgets.QPushButton(parent=self.toolbar)
        self.italicButton.setObjectName("italicButton")
        self.horizontalLayout_3.addWidget(self.italicButton)
        self.underlineButton = QtWidgets.QPushButton(parent=self.toolbar)
        self.underlineButton.setObjectName("underlineButton")
        self.horizontalLayout_3.addWidget(self.underlineButton)
        self.clearFormattingButton = QtWidgets.QPushButton(parent=self.toolbar)
        self.clearFormattingButton.setObjectName("clearFormattingButton")
        self.horizontalLayout_3.addWidget(self.clearFormattingButton)
        self.widget_4 = QtWidgets.QWidget(parent=self.toolbar)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(parent=self.widget_4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.textSizeSB = QtWidgets.QSpinBox(parent=self.widget_4)
        self.textSizeSB.setObjectName("textSizeSB")
        self.horizontalLayout_4.addWidget(self.textSizeSB)
        self.horizontalLayout_3.addWidget(self.widget_4)
        self.colorButton = QtWidgets.QPushButton(parent=self.toolbar)
        self.colorButton.setObjectName("colorButton")
        self.horizontalLayout_3.addWidget(self.colorButton)
        # self.loadButton = QtWidgets.QPushButton(parent=self.toolbar)
        # self.loadButton.setObjectName("loadButton")
        # self.horizontalLayout_3.addWidget(self.loadButton)

        self.image_toolbar = QtWidgets.QToolBar("Image Tools")

        # Кнопка вставки изображения
        self.insert_button = QtWidgets.QPushButton("Insert Image")
        self.image_toolbar.addWidget(self.insert_button)

        # Кнопка вставки из буфера обмена
        self.paste_image_button = QtWidgets.QPushButton("Paste Image")
        self.paste_image_button.setEnabled(False)
        self.image_toolbar.addWidget(self.paste_image_button)

        # Кнопки выравнивания
        self.align_group = QtWidgets.QButtonGroup(self)

        self.align_left = QtWidgets.QPushButton("Left")
        # self.align_left.setCheckable(True)

        self.align_center = QtWidgets.QPushButton("Center")
        # self.align_center.setCheckable(True)

        self.align_right = QtWidgets.QPushButton("Right")
        # self.align_right.setCheckable(True)

        self.align_group.addButton(self.align_left)
        self.align_group.addButton(self.align_center)
        self.align_group.addButton(self.align_right)

        self.image_toolbar.addWidget(self.align_left)
        self.image_toolbar.addWidget(self.align_center)
        self.image_toolbar.addWidget(self.align_right)

        image_toolbar = QtWidgets.QToolBar("Image Tools")

        # Кнопка вставки изображения
        insert_button = QtWidgets.QPushButton("Insert Image")
        insert_button.clicked.connect(self.insert_image)
        image_toolbar.addWidget(insert_button)

        # Кнопка вставки из буфера обмена
        self.paste_image_button = QtWidgets.QPushButton("Paste Image")
        self.paste_image_button.clicked.connect(self.handle_paste)
        self.paste_image_button.setEnabled(False)
        image_toolbar.addWidget(self.paste_image_button)

        # Кнопка вставки из URL
        self.insert_url_image = QtWidgets.QPushButton("Insert Image from URL")
        self.insert_url_image.clicked.connect(self.insert_image_from_url)
        self.insert_url_image.setToolTip("Ctrl+Shift+U")

        image_toolbar.addWidget(self.insert_url_image)

        # Кнопки выравнивания
        align_group = QtWidgets.QButtonGroup(self)

        align_left = QtWidgets.QPushButton("Left")
        # align_left.setCheckable(True)
        align_left.clicked.connect(lambda: self.align_image("left"))

        align_center = QtWidgets.QPushButton("Center")
        # align_center.setCheckable(True)
        align_center.clicked.connect(lambda: self.align_image("center"))

        align_right = QtWidgets.QPushButton("Right")
        # align_right.setCheckable(True)
        align_right.clicked.connect(lambda: self.align_image("right"))

        align_group.addButton(align_left)
        align_group.addButton(align_center)
        align_group.addButton(align_right)

        image_toolbar.addWidget(align_left)
        image_toolbar.addWidget(align_center)
        image_toolbar.addWidget(align_right)

        self.horizontalLayout_3.addWidget(image_toolbar)

        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)

        self.verticalLayout_2.addWidget(self.toolbar)
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.frontTE = QtWidgets.QTextEdit(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frontTE.sizePolicy().hasHeightForWidth())
        self.frontTE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.frontTE.setFont(font)
        self.frontTE.setObjectName("frontTE")
        self.verticalLayout_2.addWidget(self.frontTE)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(parent=Form)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.backTE = QtWidgets.QTextEdit(parent=self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backTE.sizePolicy().hasHeightForWidth())
        self.backTE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.backTE.setFont(font)
        self.backTE.setObjectName("backTE")
        self.verticalLayout_3.addWidget(self.backTE)
        self.verticalLayout.addWidget(self.widget_2)

        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Form)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel |
                                          QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Deck"))
        self.pushButton.setText(_translate("Form", "Deck title"))
        self.boldButton.setText(_translate("Form", "B"))
        self.italicButton.setText(_translate("Form", "I"))
        self.underlineButton.setText(_translate("Form", "U"))
        self.clearFormattingButton.setText(_translate("Form", "Clear"))
        self.label_4.setText(_translate("Form", "Size:"))
        self.colorButton.setText(_translate("Form", "Color"))
        # self.loadButton.setText(_translate("Form", "Load"))
        self.label_2.setText(_translate("Form", "Front"))
        self.label_3.setText(_translate("Form", "Back"))
        self.buttonBox.buttons()[0].setText("Add card")
