# Form implementation generated from reading ui file 'filter_window.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(305, 323)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.filterL = QtWidgets.QLabel(parent=Form)
        self.filterL.setObjectName("filterL")
        self.horizontalLayout.addWidget(self.filterL)
        self.filterValueTE = QtWidgets.QLineEdit(parent=Form)
        self.filterValueTE.setObjectName("filterValueTE")
        self.horizontalLayout.addWidget(self.filterValueTE)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.decksLW = QtWidgets.QListWidget(parent=Form)
        self.decksLW.setObjectName("decksLW")
        self.verticalLayout.addWidget(self.decksLW)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Form)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|
                                          QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.filterL.setText(_translate("Form", "Filter:"))
