# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(904, 654)
        self.verticalLayout = QtWidgets.QVBoxLayout(MainWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.programmTitle = QtWidgets.QLabel(parent=MainWindow)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.programmTitle.setFont(font)
        self.programmTitle.setObjectName("programmTitle")
        self.verticalLayout_2.addWidget(self.programmTitle)
        self.deckWidget = QtWidgets.QListWidget(parent=MainWindow)
        self.deckWidget.setObjectName("deckWidget")
        self.verticalLayout_2.addWidget(self.deckWidget)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cardAddButton = QtWidgets.QPushButton(parent=MainWindow)
        self.cardAddButton.setObjectName("cardAddButton")
        self.horizontalLayout.addWidget(self.cardAddButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.deckAddButton = QtWidgets.QPushButton(parent=MainWindow)
        self.deckAddButton.setObjectName("deckAddButton")
        self.horizontalLayout.addWidget(self.deckAddButton)

        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Maximum,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.deleteDeckButton = QtWidgets.QPushButton(parent=MainWindow)
        self.deleteDeckButton.setObjectName("deleteDeckButton")
        self.horizontalLayout.addWidget(self.deleteDeckButton)

        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.importCardsButton = QtWidgets.QPushButton(parent=MainWindow)
        self.importCardsButton.setObjectName("importCardsButton")
        self.horizontalLayout.addWidget(self.importCardsButton)

        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.cardAddButton, self.deckAddButton)
        MainWindow.setTabOrder(self.deckAddButton, self.deckWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Form"))
        self.programmTitle.setText(_translate("MainWindow", "Repetition system"))
        __sortingEnabled = self.deckWidget.isSortingEnabled()
        self.deckWidget.setSortingEnabled(False)
        self.deckWidget.setSortingEnabled(__sortingEnabled)
        self.cardAddButton.setText(_translate("MainWindow", "Add card"))
        self.deckAddButton.setText(_translate("MainWindow", "Create deck"))
        self.deleteDeckButton.setText(_translate("MainWindow", "Delete deck"))
        self.importCardsButton.setText(_translate("MainWindow", "Import"))
